--------------------------------------------------------
--  File created - Sunday-November-23-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence MESSAGES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOOKSTORE"."MESSAGES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USER_REVIEWS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOOKSTORE"."USER_REVIEWS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ADMINS
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."ADMINS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERNAME" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."CART" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(255 BYTE), 
	"PRICE" NUMBER, 
	"QUANTITY" NUMBER, 
	"IMAGE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MESSAGES
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."MESSAGES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"MESSAGE_CONTENT" VARCHAR2(4000 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MESSAGE_REPLIES
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."MESSAGE_REPLIES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MESSAGE_ID" NUMBER, 
	"REPLY_CONTENT" VARCHAR2(4000 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."ORDERS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(500 BYTE), 
	"CITY" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"PAYMENT_METHOD" VARCHAR2(50 BYTE), 
	"CARD_NUMBER" VARCHAR2(50 BYTE), 
	"EXPIRY_DATE" VARCHAR2(10 BYTE), 
	"CVV" VARCHAR2(10 BYTE), 
	"TOTAL_PRICE" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ORDER_STATUS" VARCHAR2(50 BYTE) DEFAULT 'placed'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDER_ITEMS
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."ORDER_ITEMS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ORDER_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(255 BYTE), 
	"QUANTITY" NUMBER, 
	"PRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."PRODUCTS" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(255 BYTE), 
	"PRICE" NUMBER(10,2), 
	"DESCRIPTION" CLOB, 
	"IMAGE" VARCHAR2(500 BYTE), 
	"CATEGORY" VARCHAR2(100 BYTE), 
	"STOCK" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."USERS" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_REVIEWS
--------------------------------------------------------

  CREATE TABLE "BOOKSTORE"."USER_REVIEWS" 
   (	"ID" NUMBER, 
	"USER_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(255 BYTE), 
	"RATING" NUMBER, 
	"USER_COMMENT" VARCHAR2(4000 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into BOOKSTORE.ADMINS
SET DEFINE OFF;
Insert into BOOKSTORE.ADMINS (ID,USERNAME,PASSWORD) values (1,'admin','$2b$10$mHauzCBXMRWeCaf18QTKfOzMpnqHBFlW00OMRM2LHCzxMNaS/R7A6');
REM INSERTING into BOOKSTORE.CART
SET DEFINE OFF;
REM INSERTING into BOOKSTORE.MESSAGES
SET DEFINE OFF;
Insert into BOOKSTORE.MESSAGES (ID,USER_ID,MESSAGE_CONTENT,CREATED_AT) values (1,1,'hi',to_timestamp('23-NOV-25 05.18.01.944000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into BOOKSTORE.MESSAGE_REPLIES
SET DEFINE OFF;
Insert into BOOKSTORE.MESSAGE_REPLIES (ID,MESSAGE_ID,REPLY_CONTENT,CREATED_AT) values (1,1,'hello',to_timestamp('23-NOV-25 05.19.17.396000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into BOOKSTORE.ORDERS
SET DEFINE OFF;
Insert into BOOKSTORE.ORDERS (ID,USER_ID,NAME,PHONE,EMAIL,ADDRESS,CITY,COUNTRY,PAYMENT_METHOD,CARD_NUMBER,EXPIRY_DATE,CVV,TOTAL_PRICE,CREATED_AT,ORDER_STATUS) values (1,1,'Umaima Fatima','12345678910','umaimafatima@gmail.com','Shah Faisal Colony','Karachi','Pakistan','cash',null,null,null,1000,to_timestamp('23-NOV-25 05.18.46.696000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'delivered');
REM INSERTING into BOOKSTORE.ORDER_ITEMS
SET DEFINE OFF;
Insert into BOOKSTORE.ORDER_ITEMS (ID,ORDER_ID,PRODUCT_NAME,QUANTITY,PRICE) values (1,1,'As Long As The Lemon Trees Grow',1,1000);
REM INSERTING into BOOKSTORE.PRODUCTS
SET DEFINE OFF;
Insert into BOOKSTORE.PRODUCTS (ID,NAME,PRICE,IMAGE,CATEGORY,STOCK) values (1,'As Long As The Lemon Trees Grow',1000,'lemon-tree.jpg','Fiction',10);
Insert into BOOKSTORE.PRODUCTS (ID,NAME,PRICE,IMAGE,CATEGORY,STOCK) values (2,'Maala',1200,'Maala.jpeg','Romance',10);
Insert into BOOKSTORE.PRODUCTS (ID,NAME,PRICE,IMAGE,CATEGORY,STOCK) values (3,'Jannat Kay Pattay',1100,'Jannat-Kay-Pattay.jpg','Drama',10);
Insert into BOOKSTORE.PRODUCTS (ID,NAME,PRICE,IMAGE,CATEGORY,STOCK) values (4,'The Kite Runner',850,'The Kite Runner.jpg','Fiction',10);
Insert into BOOKSTORE.PRODUCTS (ID,NAME,PRICE,IMAGE,CATEGORY,STOCK) values (5,'A Thousand Splendid Suns',900,'Splendid Suns.jpg','Fiction',10);
Insert into BOOKSTORE.PRODUCTS (ID,NAME,PRICE,IMAGE,CATEGORY,STOCK) values (6,'The Fourty Rules Of Love',1000,'Fourty Rules Of Love.webp','Spiritual',10);
Insert into BOOKSTORE.PRODUCTS (ID,NAME,PRICE,IMAGE,CATEGORY,STOCK) values (7,'The Silent Patient',995,'Silent Patient.webp','Thriller',10);
Insert into BOOKSTORE.PRODUCTS (ID,NAME,PRICE,IMAGE,CATEGORY,STOCK) values (8,'1984',600,'1984.webp','Dystopia',10);
Insert into BOOKSTORE.PRODUCTS (ID,NAME,PRICE,IMAGE,CATEGORY,STOCK) values (9,'The Fault in Our Stars',650,'fault in star.webp','Romance',10);
Insert into BOOKSTORE.PRODUCTS (ID,NAME,PRICE,IMAGE,CATEGORY,STOCK) values (10,'Reasons to Stay Alive',1450,'book1.webp','Non-fiction',10);
Insert into BOOKSTORE.PRODUCTS (ID,NAME,PRICE,IMAGE,CATEGORY,STOCK) values (11,'Rule by Fear',750,'book2.webp','Politics',10);
Insert into BOOKSTORE.PRODUCTS (ID,NAME,PRICE,IMAGE,CATEGORY,STOCK) values (12,'It Starts with Us',750,'book3.webp','Romance',10);
REM INSERTING into BOOKSTORE.USERS
SET DEFINE OFF;
Insert into BOOKSTORE.USERS (ID,USERNAME,PASSWORD) values (1,'umaima','$2b$10$fqmjJSBDlguSz62SnLYTFeCstYxIn8TPSPEEOtRp3ukBZbQ1ikLLK');
REM INSERTING into BOOKSTORE.USER_REVIEWS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Trigger USER_REVIEWS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BOOKSTORE"."USER_REVIEWS_TRIGGER" 
BEFORE INSERT ON user_reviews
FOR EACH ROW
BEGIN
  :NEW.id := user_reviews_seq.NEXTVAL;
END;

/
ALTER TRIGGER "BOOKSTORE"."USER_REVIEWS_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table MESSAGES
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."MESSAGES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."MESSAGES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."MESSAGES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."USERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."USERS" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMINS
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."ADMINS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ADMINS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ADMINS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ADMINS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOOKSTORE"."ADMINS" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" MODIFY ("PAYMENT_METHOD" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."ORDER_ITEMS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDER_ITEMS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDER_ITEMS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDER_ITEMS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDER_ITEMS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."ORDER_ITEMS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_REVIEWS
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."USER_REVIEWS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."USER_REVIEWS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."USER_REVIEWS" ADD CHECK (rating BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "BOOKSTORE"."USER_REVIEWS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MESSAGE_REPLIES
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."MESSAGE_REPLIES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."MESSAGE_REPLIES" MODIFY ("MESSAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."MESSAGE_REPLIES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."PRODUCTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."PRODUCTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."PRODUCTS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."PRODUCTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."CART" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."CART" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOOKSTORE"."CART" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."CART" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "BOOKSTORE"."USERS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MESSAGES
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."MESSAGES" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "BOOKSTORE"."USERS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MESSAGE_REPLIES
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."MESSAGE_REPLIES" ADD FOREIGN KEY ("MESSAGE_ID")
	  REFERENCES "BOOKSTORE"."MESSAGES" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."ORDERS" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "BOOKSTORE"."USERS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."ORDER_ITEMS" ADD FOREIGN KEY ("ORDER_ID")
	  REFERENCES "BOOKSTORE"."ORDERS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_REVIEWS
--------------------------------------------------------

  ALTER TABLE "BOOKSTORE"."USER_REVIEWS" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "BOOKSTORE"."USERS" ("ID") ENABLE;
