--USER PORTAL
CREATE TABLE USERS (
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  USERNAME VARCHAR2(50) UNIQUE,
  PASSWORD VARCHAR2(255),
  PRIMARY KEY (ID)
);
SELECT * FROM users;


CREATE TABLE CART (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  product_name VARCHAR2(255),
  price NUMBER,
  quantity NUMBER,
  image VARCHAR2(255), 
  FOREIGN KEY(user_id) REFERENCES users(ID) ON DELETE CASCADE
);
SELECT * FROM cart;


CREATE TABLE orders (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  name VARCHAR2(255) NOT NULL,
  phone VARCHAR2(50) NOT NULL,
  email VARCHAR2(255) NOT NULL,
  address VARCHAR2(500) NOT NULL,
  city VARCHAR2(100) NOT NULL,
  country VARCHAR2(100) NOT NULL,
  payment_method VARCHAR2(50) NOT NULL,
  card_number VARCHAR2(50), -- optional
  expiry_date VARCHAR2(10), -- optional
  cvv VARCHAR2(10),         -- optional
  total_price NUMBER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
ALTER TABLE orders ADD (order_status VARCHAR2(50) DEFAULT 'placed');
SELECT * FROM orders;


--MyOrder ki details show krny ka liya 
CREATE TABLE order_items (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_id NUMBER NOT NULL,
  product_name VARCHAR2(255) NOT NULL,
  quantity NUMBER NOT NULL,
  price NUMBER NOT NULL,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);
SELECT * FROM order_items;


CREATE TABLE messages (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    message_content VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE SEQUENCE messages_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
ALTER TABLE messages MODIFY id DEFAULT messages_seq.NEXTVAL;
SELECT * FROM messages;


CREATE TABLE user_reviews (
    id NUMBER PRIMARY KEY,
    user_id NUMBER NOT NULL,
    product_name VARCHAR2(255) NOT NULL,
    rating NUMBER CHECK (rating BETWEEN 1 AND 5),
    user_comment VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE SEQUENCE user_reviews_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER user_reviews_trigger
BEFORE INSERT ON user_reviews
FOR EACH ROW
BEGIN
  :NEW.id := user_reviews_seq.NEXTVAL;
END;
/

--ADMIN PORTAL
CREATE TABLE admins (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username VARCHAR2(255) UNIQUE NOT NULL,
  password VARCHAR2(255) NOT NULL
);
ALTER TABLE admins MODIFY password VARCHAR2(1000);
DELETE FROM admins;
INSERT INTO admins (username, password)
VALUES ('admin', '$2b$10$mHauzCBXMRWeCaf18QTKfOzMpnqHBFlW00OMRM2LHCzxMNaS/R7A6');
COMMIT;

CREATE TABLE products (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255) NOT NULL,
  price NUMBER(10,2) NOT NULL,
  description CLOB,
  image VARCHAR2(500),
  category VARCHAR2(100),
  stock NUMBER DEFAULT 0
);
INSERT INTO products (name, price, description, image, category, stock) VALUES ('As Long As The Lemon Trees Grow', 1000, 'A touching novel.', 'lemon-tree.jpg', 'Fiction', 10);
INSERT INTO products (name, price, description, image, category, stock) VALUES ('Maala', 1200, 'A classic love story.', 'Maala.jpeg', 'Romance', 10);
INSERT INTO products (name, price, description, image, category, stock) VALUES ('Jannat Kay Pattay', 1100, 'A spiritual journey.', 'Jannat-Kay-Pattay.jpg', 'Drama', 10);
INSERT INTO products (name, price, description, image, category, stock) VALUES ('The Kite Runner', 850, 'A tale of friendship.', 'The Kite Runner.jpg', 'Fiction', 10);
INSERT INTO products (name, price, description, image, category, stock) VALUES ('A Thousand Splendid Suns', 900, 'A heartbreaking story.', 'Splendid Suns.jpg', 'Fiction', 10);
INSERT INTO products (name, price, description, image, category, stock) VALUES ('The Fourty Rules Of Love', 1000, 'Mystical and philosophical.', 'Fourty Rules Of Love.webp', 'Spiritual', 10);
INSERT INTO products (name, price, description, image, category, stock) VALUES ('The Silent Patient', 995, 'Psychological thriller.', 'Silent Patient.webp', 'Thriller', 10);
INSERT INTO products (name, price, description, image, category, stock) VALUES ('1984', 600, 'Dystopian future.', '1984.webp', 'Dystopia', 10);
INSERT INTO products (name, price, description, image, category, stock) VALUES ('The Fault in Our Stars', 650, 'Teen love story.', 'fault in star.webp', 'Romance', 10);
INSERT INTO products (name, price, description, image, category, stock) VALUES ('Reasons to Stay Alive', 1450, 'Mental health memoir.', 'book1.webp', 'Non-fiction', 10);
INSERT INTO products (name, price, description, image, category, stock) VALUES ('Rule by Fear', 750, 'Political analysis.', 'book2.webp', 'Politics', 10);
INSERT INTO products (name, price, description, image, category, stock) VALUES ('It Starts with Us', 700, 'Emotional drama.', 'book3.webp', 'Romance', 10);
COMMIT;
SELECT * FROM products;

-- Admin replies table
CREATE TABLE message_replies (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    message_id NUMBER NOT NULL,
    reply_content VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE
);

